export const STUDENT_RESULT_REQUEST = "STUDENT_RESULT_REQUEST";
export const STUDENT_RESULT_SUCCESS = "STUDENT_RESULT_SUCCESS";
export const STUDENT_RESULT_FAIL = "STUDENT_RESULT_FAIL";

export const ADD_SUBJECT_REQUEST = "ADD_SUBJECT_REQUEST";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAIL = "ADD_SUBJECT_FAIL";

export const DELETE_SUBJECT_REQUEST = "DELETE_SUBJECT_REQUEST";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAIL = "DELETE_SUBJECT_FAIL";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";

export const ADMIN_RESULT_REQUEST = "ADMIN_RESULT_REQUEST";
export const ADMIN_RESULT_SUCCESS = "ADMIN_RESULT_SUCCESS";
export const ADMIN_RESULT_FAIL = "ADMIN_RESULT_FAIL";

export const EDIT_RESULT_REQUEST = "EDIT_RESULT_REQUEST";
export const EDIT_RESULT_SUCCESS = "EDIT_RESULT_SUCCESS";
export const EDIT_RESULT_FAIL = "EDIT_RESULT_FAIL";

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";
