export const STUDENT_RESULT_REQUEST = "STUDENT_RESULT_REQUEST";
export const STUDENT_RESULT_SUCCESS = "STUDENT_RESULT_SUCCESS";
export const STUDENT_RESULT_FAIL = "STUDENT_RESULT_FAIL";

export const ADMIN_RESULT_REQUEST = "ADMIN_RESULT_REQUEST";
export const ADMIN_RESULT_SUCCESS = "ADMIN_RESULT_SUCCESS";
export const ADMIN_RESULT_FAIL = "ADMIN_RESULT_FAIL";

export const EDIT_RESULT_REQUEST = "EDIT_RESULT_REQUEST";
export const EDIT_RESULT_SUCCESS = "EDIT_RESULT_SUCCESS";
export const EDIT_RESULT_FAIL = "EDIT_RESULT_FAIL";

export const ADD_STUDENT_REQUEST = "ADD_STUDENT_REQUEST";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";
